---
source: parser/src/lexer/mod.rs
description: "# Test case to check that we return correct error when two python statements are on the same line\n\ndef foo():\n    x = 1; y = 2\n    return x + y\n\ndef bar():\n    # TODO(parser): enable after error handling\n    # x = 1 y = 2\n    return x + y\n\n# TODO(parser): enable after error handling\n# a = 1  b = 2\n"
input_file: parser/test_data/inputs/separate_statements.py
---
0,97: Comment
97,98: NL
98,99: NL
99,102: Def
103,106: Identifier   foo
106,107: (
107,108: )
108,109: :
109,110: NewLine
110,114: Indent
114,115: Identifier   x
116,117: =
118,119: Integer   1
119,120: ;
121,122: Identifier   y
123,124: =
125,126: Integer   2
126,127: NewLine
131,137: Return
138,139: Identifier   x
140,141: +
142,143: Identifier   y
143,144: NewLine
144,145: NL
145,145: Dedent
145,148: Def
149,152: Identifier   bar
152,153: (
153,154: )
154,155: :
155,156: NewLine
160,203: Comment
203,204: NL
208,221: Comment
221,222: NL
222,226: Indent
226,232: Return
233,234: Identifier   x
235,236: +
237,238: Identifier   y
238,239: NewLine
239,240: NL
240,283: Comment
283,284: NL
284,298: Comment
298,299: NL
299,299: Dedent
